/**
 * Inlines @stvor/core into verifier/index.html so the page is a SINGLE
 * self-contained file that verifies receipts fully offline — including when
 * opened straight from disk (file://), where external ES-module imports are
 * blocked by the browser. Idempotent: replaces everything between the markers.
 *
 *   bun run scripts/build-verifier.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const HTML = join(ROOT, 'verifier/index.html')
const START = '// __STVOR_CORE_INLINE_START__'
const END = '// __STVOR_CORE_INLINE_END__'

const built = await Bun.build({
  entrypoints: [join(ROOT, 'stvor-core/src/index.ts')],
  target: 'browser',
  format: 'esm',
})
if (!built.success) {
  console.error(built.logs.join('\n'))
  process.exit(1)
}
let bundle = await built.outputs[0].text()
// Never let bundle bytes close the <script> tag early.
bundle = bundle.replace(/<\/(script)/gi, '<\\/$1')

let html = readFileSync(HTML, 'utf8')
const startIdx = html.indexOf(START)
const endIdx = html.indexOf(END)
if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
  console.error('markers not found in verifier/index.html')
  process.exit(1)
}
const before = html.slice(0, startIdx)
const after = html.slice(endIdx + END.length)
html =
  before +
  START +
  ' (generated by build:verifier — do not edit between markers)\n' +
  bundle +
  '\n      ' +
  END +
  after

writeFileSync(HTML, html)
console.log(`Inlined @stvor/core (${bundle.length} bytes) into verifier/index.html`)
